packages:
  - app
  - backend
  - components
  - hooks
  - lib
  - types
  - docs
  - database
  - scripts
  - design-system
  - design-tokens
  - package-ui
  - styles

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
